# Generated by Django 5.2.14 on 2026-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project', models.CharField()),
                ('reporter', models.TextField()),
                ('assignee', models.TextField()),
                ('status', models.TextField(choices=[('TODO', 'todo'), ('IN_PROGRESS', 'in_progress'), ('TESTING', 'testing'), ('DONE', 'done')], max_length=20)),
                ('priority', models.TextField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high'), ('URGENT', 'urgent'), ('CRITICAL', 'critical')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
