# Generated by Django 5.2.10 on 2026-05-31 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
